// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/CPU-commits/Template_Go-EventDriven/src/auth/model"
	"github.com/CPU-commits/Template_Go-EventDriven/src/auth/repository/session_repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionRepository creates a new instance of MockSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionRepository {
	mock := &MockSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionRepository is an autogenerated mock type for the SessionRepository type
type MockSessionRepository struct {
	mock.Mock
}

type MockSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionRepository) EXPECT() *MockSessionRepository_Expecter {
	return &MockSessionRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) Delete(criteria *session_repository.SessionCriteria) error {
	ret := _mock.Called(criteria)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*session_repository.SessionCriteria) error); ok {
		r0 = returnFunc(criteria)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSessionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - criteria
func (_e *MockSessionRepository_Expecter) Delete(criteria interface{}) *MockSessionRepository_Delete_Call {
	return &MockSessionRepository_Delete_Call{Call: _e.mock.On("Delete", criteria)}
}

func (_c *MockSessionRepository_Delete_Call) Run(run func(criteria *session_repository.SessionCriteria)) *MockSessionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*session_repository.SessionCriteria))
	})
	return _c
}

func (_c *MockSessionRepository_Delete_Call) Return(err error) *MockSessionRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_Delete_Call) RunAndReturn(run func(criteria *session_repository.SessionCriteria) error) *MockSessionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) Exists(criteria *session_repository.SessionCriteria) (int64, error) {
	ret := _mock.Called(criteria)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*session_repository.SessionCriteria) (int64, error)); ok {
		return returnFunc(criteria)
	}
	if returnFunc, ok := ret.Get(0).(func(*session_repository.SessionCriteria) int64); ok {
		r0 = returnFunc(criteria)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(*session_repository.SessionCriteria) error); ok {
		r1 = returnFunc(criteria)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockSessionRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - criteria
func (_e *MockSessionRepository_Expecter) Exists(criteria interface{}) *MockSessionRepository_Exists_Call {
	return &MockSessionRepository_Exists_Call{Call: _e.mock.On("Exists", criteria)}
}

func (_c *MockSessionRepository_Exists_Call) Run(run func(criteria *session_repository.SessionCriteria)) *MockSessionRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*session_repository.SessionCriteria))
	})
	return _c
}

func (_c *MockSessionRepository_Exists_Call) Return(id int64, err error) *MockSessionRepository_Exists_Call {
	_c.Call.Return(id, err)
	return _c
}

func (_c *MockSessionRepository_Exists_Call) RunAndReturn(run func(criteria *session_repository.SessionCriteria) (int64, error)) *MockSessionRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// InsertOne provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) InsertOne(session model.Session) (int64, error) {
	ret := _mock.Called(session)

	if len(ret) == 0 {
		panic("no return value specified for InsertOne")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(model.Session) (int64, error)); ok {
		return returnFunc(session)
	}
	if returnFunc, ok := ret.Get(0).(func(model.Session) int64); ok {
		r0 = returnFunc(session)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(model.Session) error); ok {
		r1 = returnFunc(session)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepository_InsertOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertOne'
type MockSessionRepository_InsertOne_Call struct {
	*mock.Call
}

// InsertOne is a helper method to define mock.On call
//   - session
func (_e *MockSessionRepository_Expecter) InsertOne(session interface{}) *MockSessionRepository_InsertOne_Call {
	return &MockSessionRepository_InsertOne_Call{Call: _e.mock.On("InsertOne", session)}
}

func (_c *MockSessionRepository_InsertOne_Call) Run(run func(session model.Session)) *MockSessionRepository_InsertOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Session))
	})
	return _c
}

func (_c *MockSessionRepository_InsertOne_Call) Return(id int64, err error) *MockSessionRepository_InsertOne_Call {
	_c.Call.Return(id, err)
	return _c
}

func (_c *MockSessionRepository_InsertOne_Call) RunAndReturn(run func(session model.Session) (int64, error)) *MockSessionRepository_InsertOne_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) Update(criteria *session_repository.SessionCriteria, data session_repository.SessionUpdateData) error {
	ret := _mock.Called(criteria, data)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*session_repository.SessionCriteria, session_repository.SessionUpdateData) error); ok {
		r0 = returnFunc(criteria, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSessionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - criteria
//   - data
func (_e *MockSessionRepository_Expecter) Update(criteria interface{}, data interface{}) *MockSessionRepository_Update_Call {
	return &MockSessionRepository_Update_Call{Call: _e.mock.On("Update", criteria, data)}
}

func (_c *MockSessionRepository_Update_Call) Run(run func(criteria *session_repository.SessionCriteria, data session_repository.SessionUpdateData)) *MockSessionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*session_repository.SessionCriteria), args[1].(session_repository.SessionUpdateData))
	})
	return _c
}

func (_c *MockSessionRepository_Update_Call) Return(err error) *MockSessionRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_Update_Call) RunAndReturn(run func(criteria *session_repository.SessionCriteria, data session_repository.SessionUpdateData) error) *MockSessionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
