FROM golang:1.23.1-alpine3.20

RUN export GO111MODULE="on"

RUN go install github.com/githubnemo/CompileDaemon@latest

WORKDIR /app

COPY . /app

RUN go mod download

ENTRYPOINT CompileDaemon -polling --build="go build main.go" --command=./main
