services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    depends_on:
      - nats-js
      - pg
    networks:
      - micro_services_network

  nats-js:
    image: nats:2.10-scratch
    ports:
      - 4222:4222
    command: "-js"
    networks:
      - micro_services_network
  pg:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    container_name: pg
    volumes:
      - "db_pg:/var/lib/postgresql/data"
    networks:
      - micro_services_network
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: defaultdb

networks:
  micro_services_network:
    external: true
    driver: bridge

volumes:
  db_pg:
