// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Accesses       string
	Auths          string
	RecoveryCodes  string
	RecoveryTokens string
	RolesUsers     string
	Sessions       string
	Users          string
}{
	Accesses:       "accesses",
	Auths:          "auths",
	RecoveryCodes:  "recovery_codes",
	RecoveryTokens: "recovery_tokens",
	RolesUsers:     "roles_users",
	Sessions:       "sessions",
	Users:          "users",
}
