// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Accesses", testAccessesUpsert)

	t.Run("Auths", testAuthsUpsert)

	t.Run("RecoveryCodes", testRecoveryCodesUpsert)

	t.Run("RecoveryTokens", testRecoveryTokensUpsert)

	t.Run("RolesUsers", testRolesUsersUpsert)

	t.Run("Sessions", testSessionsUpsert)

	t.Run("Users", testUsersUpsert)
}
