// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// RecoveryToken is an object representing the database table.
type RecoveryToken struct {
	ID        int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	Token     string    `boil:"token" json:"token" toml:"token" yaml:"token"`
	IDUser    int64     `boil:"id_user" json:"id_user" toml:"id_user" yaml:"id_user"`
	IsUsed    bool      `boil:"is_used" json:"is_used" toml:"is_used" yaml:"is_used"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	ExpiresAt time.Time `boil:"expires_at" json:"expires_at" toml:"expires_at" yaml:"expires_at"`

	R *recoveryTokenR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L recoveryTokenL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var RecoveryTokenColumns = struct {
	ID        string
	Token     string
	IDUser    string
	IsUsed    string
	CreatedAt string
	ExpiresAt string
}{
	ID:        "id",
	Token:     "token",
	IDUser:    "id_user",
	IsUsed:    "is_used",
	CreatedAt: "created_at",
	ExpiresAt: "expires_at",
}

var RecoveryTokenTableColumns = struct {
	ID        string
	Token     string
	IDUser    string
	IsUsed    string
	CreatedAt string
	ExpiresAt string
}{
	ID:        "recovery_tokens.id",
	Token:     "recovery_tokens.token",
	IDUser:    "recovery_tokens.id_user",
	IsUsed:    "recovery_tokens.is_used",
	CreatedAt: "recovery_tokens.created_at",
	ExpiresAt: "recovery_tokens.expires_at",
}

// Generated where

var RecoveryTokenWhere = struct {
	ID        whereHelperint64
	Token     whereHelperstring
	IDUser    whereHelperint64
	IsUsed    whereHelperbool
	CreatedAt whereHelpertime_Time
	ExpiresAt whereHelpertime_Time
}{
	ID:        whereHelperint64{field: "\"recovery_tokens\".\"id\""},
	Token:     whereHelperstring{field: "\"recovery_tokens\".\"token\""},
	IDUser:    whereHelperint64{field: "\"recovery_tokens\".\"id_user\""},
	IsUsed:    whereHelperbool{field: "\"recovery_tokens\".\"is_used\""},
	CreatedAt: whereHelpertime_Time{field: "\"recovery_tokens\".\"created_at\""},
	ExpiresAt: whereHelpertime_Time{field: "\"recovery_tokens\".\"expires_at\""},
}

// RecoveryTokenRels is where relationship names are stored.
var RecoveryTokenRels = struct {
	IDUserUser string
}{
	IDUserUser: "IDUserUser",
}

// recoveryTokenR is where relationships are stored.
type recoveryTokenR struct {
	IDUserUser *User `boil:"IDUserUser" json:"IDUserUser" toml:"IDUserUser" yaml:"IDUserUser"`
}

// NewStruct creates a new relationship struct
func (*recoveryTokenR) NewStruct() *recoveryTokenR {
	return &recoveryTokenR{}
}

func (r *recoveryTokenR) GetIDUserUser() *User {
	if r == nil {
		return nil
	}
	return r.IDUserUser
}

// recoveryTokenL is where Load methods for each relationship are stored.
type recoveryTokenL struct{}

var (
	recoveryTokenAllColumns            = []string{"id", "token", "id_user", "is_used", "created_at", "expires_at"}
	recoveryTokenColumnsWithoutDefault = []string{"token", "id_user", "expires_at"}
	recoveryTokenColumnsWithDefault    = []string{"id", "is_used", "created_at"}
	recoveryTokenPrimaryKeyColumns     = []string{"id"}
	recoveryTokenGeneratedColumns      = []string{}
)

type (
	// RecoveryTokenSlice is an alias for a slice of pointers to RecoveryToken.
	// This should almost always be used instead of []RecoveryToken.
	RecoveryTokenSlice []*RecoveryToken
	// RecoveryTokenHook is the signature for custom RecoveryToken hook methods
	RecoveryTokenHook func(context.Context, boil.ContextExecutor, *RecoveryToken) error

	recoveryTokenQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	recoveryTokenType                 = reflect.TypeOf(&RecoveryToken{})
	recoveryTokenMapping              = queries.MakeStructMapping(recoveryTokenType)
	recoveryTokenPrimaryKeyMapping, _ = queries.BindMapping(recoveryTokenType, recoveryTokenMapping, recoveryTokenPrimaryKeyColumns)
	recoveryTokenInsertCacheMut       sync.RWMutex
	recoveryTokenInsertCache          = make(map[string]insertCache)
	recoveryTokenUpdateCacheMut       sync.RWMutex
	recoveryTokenUpdateCache          = make(map[string]updateCache)
	recoveryTokenUpsertCacheMut       sync.RWMutex
	recoveryTokenUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var recoveryTokenAfterSelectMu sync.Mutex
var recoveryTokenAfterSelectHooks []RecoveryTokenHook

var recoveryTokenBeforeInsertMu sync.Mutex
var recoveryTokenBeforeInsertHooks []RecoveryTokenHook
var recoveryTokenAfterInsertMu sync.Mutex
var recoveryTokenAfterInsertHooks []RecoveryTokenHook

var recoveryTokenBeforeUpdateMu sync.Mutex
var recoveryTokenBeforeUpdateHooks []RecoveryTokenHook
var recoveryTokenAfterUpdateMu sync.Mutex
var recoveryTokenAfterUpdateHooks []RecoveryTokenHook

var recoveryTokenBeforeDeleteMu sync.Mutex
var recoveryTokenBeforeDeleteHooks []RecoveryTokenHook
var recoveryTokenAfterDeleteMu sync.Mutex
var recoveryTokenAfterDeleteHooks []RecoveryTokenHook

var recoveryTokenBeforeUpsertMu sync.Mutex
var recoveryTokenBeforeUpsertHooks []RecoveryTokenHook
var recoveryTokenAfterUpsertMu sync.Mutex
var recoveryTokenAfterUpsertHooks []RecoveryTokenHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *RecoveryToken) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range recoveryTokenAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *RecoveryToken) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range recoveryTokenBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *RecoveryToken) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range recoveryTokenAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *RecoveryToken) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range recoveryTokenBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *RecoveryToken) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range recoveryTokenAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *RecoveryToken) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range recoveryTokenBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *RecoveryToken) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range recoveryTokenAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *RecoveryToken) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range recoveryTokenBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *RecoveryToken) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range recoveryTokenAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddRecoveryTokenHook registers your hook function for all future operations.
func AddRecoveryTokenHook(hookPoint boil.HookPoint, recoveryTokenHook RecoveryTokenHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		recoveryTokenAfterSelectMu.Lock()
		recoveryTokenAfterSelectHooks = append(recoveryTokenAfterSelectHooks, recoveryTokenHook)
		recoveryTokenAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		recoveryTokenBeforeInsertMu.Lock()
		recoveryTokenBeforeInsertHooks = append(recoveryTokenBeforeInsertHooks, recoveryTokenHook)
		recoveryTokenBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		recoveryTokenAfterInsertMu.Lock()
		recoveryTokenAfterInsertHooks = append(recoveryTokenAfterInsertHooks, recoveryTokenHook)
		recoveryTokenAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		recoveryTokenBeforeUpdateMu.Lock()
		recoveryTokenBeforeUpdateHooks = append(recoveryTokenBeforeUpdateHooks, recoveryTokenHook)
		recoveryTokenBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		recoveryTokenAfterUpdateMu.Lock()
		recoveryTokenAfterUpdateHooks = append(recoveryTokenAfterUpdateHooks, recoveryTokenHook)
		recoveryTokenAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		recoveryTokenBeforeDeleteMu.Lock()
		recoveryTokenBeforeDeleteHooks = append(recoveryTokenBeforeDeleteHooks, recoveryTokenHook)
		recoveryTokenBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		recoveryTokenAfterDeleteMu.Lock()
		recoveryTokenAfterDeleteHooks = append(recoveryTokenAfterDeleteHooks, recoveryTokenHook)
		recoveryTokenAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		recoveryTokenBeforeUpsertMu.Lock()
		recoveryTokenBeforeUpsertHooks = append(recoveryTokenBeforeUpsertHooks, recoveryTokenHook)
		recoveryTokenBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		recoveryTokenAfterUpsertMu.Lock()
		recoveryTokenAfterUpsertHooks = append(recoveryTokenAfterUpsertHooks, recoveryTokenHook)
		recoveryTokenAfterUpsertMu.Unlock()
	}
}

// One returns a single recoveryToken record from the query.
func (q recoveryTokenQuery) One(ctx context.Context, exec boil.ContextExecutor) (*RecoveryToken, error) {
	o := &RecoveryToken{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for recovery_tokens")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all RecoveryToken records from the query.
func (q recoveryTokenQuery) All(ctx context.Context, exec boil.ContextExecutor) (RecoveryTokenSlice, error) {
	var o []*RecoveryToken

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to RecoveryToken slice")
	}

	if len(recoveryTokenAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all RecoveryToken records in the query.
func (q recoveryTokenQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count recovery_tokens rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q recoveryTokenQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if recovery_tokens exists")
	}

	return count > 0, nil
}

// IDUserUser pointed to by the foreign key.
func (o *RecoveryToken) IDUserUser(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.IDUser),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadIDUserUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (recoveryTokenL) LoadIDUserUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeRecoveryToken interface{}, mods queries.Applicator) error {
	var slice []*RecoveryToken
	var object *RecoveryToken

	if singular {
		var ok bool
		object, ok = maybeRecoveryToken.(*RecoveryToken)
		if !ok {
			object = new(RecoveryToken)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeRecoveryToken)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeRecoveryToken))
			}
		}
	} else {
		s, ok := maybeRecoveryToken.(*[]*RecoveryToken)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeRecoveryToken)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeRecoveryToken))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &recoveryTokenR{}
		}
		args[object.IDUser] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &recoveryTokenR{}
			}

			args[obj.IDUser] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.IDUserUser = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.IDUserRecoveryTokens = append(foreign.R.IDUserRecoveryTokens, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.IDUser == foreign.ID {
				local.R.IDUserUser = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.IDUserRecoveryTokens = append(foreign.R.IDUserRecoveryTokens, local)
				break
			}
		}
	}

	return nil
}

// SetIDUserUser of the recoveryToken to the related item.
// Sets o.R.IDUserUser to related.
// Adds o to related.R.IDUserRecoveryTokens.
func (o *RecoveryToken) SetIDUserUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"recovery_tokens\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"id_user"}),
		strmangle.WhereClause("\"", "\"", 2, recoveryTokenPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.IDUser = related.ID
	if o.R == nil {
		o.R = &recoveryTokenR{
			IDUserUser: related,
		}
	} else {
		o.R.IDUserUser = related
	}

	if related.R == nil {
		related.R = &userR{
			IDUserRecoveryTokens: RecoveryTokenSlice{o},
		}
	} else {
		related.R.IDUserRecoveryTokens = append(related.R.IDUserRecoveryTokens, o)
	}

	return nil
}

// RecoveryTokens retrieves all the records using an executor.
func RecoveryTokens(mods ...qm.QueryMod) recoveryTokenQuery {
	mods = append(mods, qm.From("\"recovery_tokens\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"recovery_tokens\".*"})
	}

	return recoveryTokenQuery{q}
}

// FindRecoveryToken retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindRecoveryToken(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*RecoveryToken, error) {
	recoveryTokenObj := &RecoveryToken{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"recovery_tokens\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, recoveryTokenObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from recovery_tokens")
	}

	if err = recoveryTokenObj.doAfterSelectHooks(ctx, exec); err != nil {
		return recoveryTokenObj, err
	}

	return recoveryTokenObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *RecoveryToken) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no recovery_tokens provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(recoveryTokenColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	recoveryTokenInsertCacheMut.RLock()
	cache, cached := recoveryTokenInsertCache[key]
	recoveryTokenInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			recoveryTokenAllColumns,
			recoveryTokenColumnsWithDefault,
			recoveryTokenColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(recoveryTokenType, recoveryTokenMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(recoveryTokenType, recoveryTokenMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"recovery_tokens\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"recovery_tokens\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into recovery_tokens")
	}

	if !cached {
		recoveryTokenInsertCacheMut.Lock()
		recoveryTokenInsertCache[key] = cache
		recoveryTokenInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the RecoveryToken.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *RecoveryToken) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	recoveryTokenUpdateCacheMut.RLock()
	cache, cached := recoveryTokenUpdateCache[key]
	recoveryTokenUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			recoveryTokenAllColumns,
			recoveryTokenPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update recovery_tokens, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"recovery_tokens\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, recoveryTokenPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(recoveryTokenType, recoveryTokenMapping, append(wl, recoveryTokenPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update recovery_tokens row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for recovery_tokens")
	}

	if !cached {
		recoveryTokenUpdateCacheMut.Lock()
		recoveryTokenUpdateCache[key] = cache
		recoveryTokenUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q recoveryTokenQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for recovery_tokens")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for recovery_tokens")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o RecoveryTokenSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), recoveryTokenPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"recovery_tokens\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, recoveryTokenPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in recoveryToken slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all recoveryToken")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *RecoveryToken) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no recovery_tokens provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(recoveryTokenColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	recoveryTokenUpsertCacheMut.RLock()
	cache, cached := recoveryTokenUpsertCache[key]
	recoveryTokenUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			recoveryTokenAllColumns,
			recoveryTokenColumnsWithDefault,
			recoveryTokenColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			recoveryTokenAllColumns,
			recoveryTokenPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert recovery_tokens, could not build update column list")
		}

		ret := strmangle.SetComplement(recoveryTokenAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(recoveryTokenPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert recovery_tokens, could not build conflict column list")
			}

			conflict = make([]string, len(recoveryTokenPrimaryKeyColumns))
			copy(conflict, recoveryTokenPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"recovery_tokens\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(recoveryTokenType, recoveryTokenMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(recoveryTokenType, recoveryTokenMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert recovery_tokens")
	}

	if !cached {
		recoveryTokenUpsertCacheMut.Lock()
		recoveryTokenUpsertCache[key] = cache
		recoveryTokenUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single RecoveryToken record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *RecoveryToken) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no RecoveryToken provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), recoveryTokenPrimaryKeyMapping)
	sql := "DELETE FROM \"recovery_tokens\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from recovery_tokens")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for recovery_tokens")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q recoveryTokenQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no recoveryTokenQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from recovery_tokens")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for recovery_tokens")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o RecoveryTokenSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(recoveryTokenBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), recoveryTokenPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"recovery_tokens\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, recoveryTokenPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from recoveryToken slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for recovery_tokens")
	}

	if len(recoveryTokenAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *RecoveryToken) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindRecoveryToken(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *RecoveryTokenSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := RecoveryTokenSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), recoveryTokenPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"recovery_tokens\".* FROM \"recovery_tokens\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, recoveryTokenPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in RecoveryTokenSlice")
	}

	*o = slice

	return nil
}

// RecoveryTokenExists checks if the RecoveryToken row exists.
func RecoveryTokenExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"recovery_tokens\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if recovery_tokens exists")
	}

	return exists, nil
}

// Exists checks if the RecoveryToken row exists.
func (o *RecoveryToken) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return RecoveryTokenExists(ctx, exec, o.ID)
}
