// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

func testRecoveryCodesUpsert(t *testing.T) {
	t.Parallel()

	if len(recoveryCodeAllColumns) == len(recoveryCodePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := RecoveryCode{}
	if err = randomize.Struct(seed, &o, recoveryCodeDBTypes, true); err != nil {
		t.Errorf("Unable to randomize RecoveryCode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert RecoveryCode: %s", err)
	}

	count, err := RecoveryCodes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, recoveryCodeDBTypes, false, recoveryCodePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize RecoveryCode struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert RecoveryCode: %s", err)
	}

	count, err = RecoveryCodes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testRecoveryCodes(t *testing.T) {
	t.Parallel()

	query := RecoveryCodes()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testRecoveryCodesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RecoveryCode{}
	if err = randomize.Struct(seed, o, recoveryCodeDBTypes, true, recoveryCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecoveryCode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := RecoveryCodes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRecoveryCodesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RecoveryCode{}
	if err = randomize.Struct(seed, o, recoveryCodeDBTypes, true, recoveryCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecoveryCode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := RecoveryCodes().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := RecoveryCodes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRecoveryCodesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RecoveryCode{}
	if err = randomize.Struct(seed, o, recoveryCodeDBTypes, true, recoveryCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecoveryCode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RecoveryCodeSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := RecoveryCodes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRecoveryCodesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RecoveryCode{}
	if err = randomize.Struct(seed, o, recoveryCodeDBTypes, true, recoveryCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecoveryCode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := RecoveryCodeExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if RecoveryCode exists: %s", err)
	}
	if !e {
		t.Errorf("Expected RecoveryCodeExists to return true, but got false.")
	}
}

func testRecoveryCodesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RecoveryCode{}
	if err = randomize.Struct(seed, o, recoveryCodeDBTypes, true, recoveryCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecoveryCode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	recoveryCodeFound, err := FindRecoveryCode(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if recoveryCodeFound == nil {
		t.Error("want a record, got nil")
	}
}

func testRecoveryCodesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RecoveryCode{}
	if err = randomize.Struct(seed, o, recoveryCodeDBTypes, true, recoveryCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecoveryCode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = RecoveryCodes().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testRecoveryCodesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RecoveryCode{}
	if err = randomize.Struct(seed, o, recoveryCodeDBTypes, true, recoveryCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecoveryCode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := RecoveryCodes().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testRecoveryCodesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	recoveryCodeOne := &RecoveryCode{}
	recoveryCodeTwo := &RecoveryCode{}
	if err = randomize.Struct(seed, recoveryCodeOne, recoveryCodeDBTypes, false, recoveryCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecoveryCode struct: %s", err)
	}
	if err = randomize.Struct(seed, recoveryCodeTwo, recoveryCodeDBTypes, false, recoveryCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecoveryCode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = recoveryCodeOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = recoveryCodeTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := RecoveryCodes().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testRecoveryCodesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	recoveryCodeOne := &RecoveryCode{}
	recoveryCodeTwo := &RecoveryCode{}
	if err = randomize.Struct(seed, recoveryCodeOne, recoveryCodeDBTypes, false, recoveryCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecoveryCode struct: %s", err)
	}
	if err = randomize.Struct(seed, recoveryCodeTwo, recoveryCodeDBTypes, false, recoveryCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecoveryCode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = recoveryCodeOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = recoveryCodeTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RecoveryCodes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func recoveryCodeBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *RecoveryCode) error {
	*o = RecoveryCode{}
	return nil
}

func recoveryCodeAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *RecoveryCode) error {
	*o = RecoveryCode{}
	return nil
}

func recoveryCodeAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *RecoveryCode) error {
	*o = RecoveryCode{}
	return nil
}

func recoveryCodeBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *RecoveryCode) error {
	*o = RecoveryCode{}
	return nil
}

func recoveryCodeAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *RecoveryCode) error {
	*o = RecoveryCode{}
	return nil
}

func recoveryCodeBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *RecoveryCode) error {
	*o = RecoveryCode{}
	return nil
}

func recoveryCodeAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *RecoveryCode) error {
	*o = RecoveryCode{}
	return nil
}

func recoveryCodeBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *RecoveryCode) error {
	*o = RecoveryCode{}
	return nil
}

func recoveryCodeAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *RecoveryCode) error {
	*o = RecoveryCode{}
	return nil
}

func testRecoveryCodesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &RecoveryCode{}
	o := &RecoveryCode{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, recoveryCodeDBTypes, false); err != nil {
		t.Errorf("Unable to randomize RecoveryCode object: %s", err)
	}

	AddRecoveryCodeHook(boil.BeforeInsertHook, recoveryCodeBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	recoveryCodeBeforeInsertHooks = []RecoveryCodeHook{}

	AddRecoveryCodeHook(boil.AfterInsertHook, recoveryCodeAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	recoveryCodeAfterInsertHooks = []RecoveryCodeHook{}

	AddRecoveryCodeHook(boil.AfterSelectHook, recoveryCodeAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	recoveryCodeAfterSelectHooks = []RecoveryCodeHook{}

	AddRecoveryCodeHook(boil.BeforeUpdateHook, recoveryCodeBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	recoveryCodeBeforeUpdateHooks = []RecoveryCodeHook{}

	AddRecoveryCodeHook(boil.AfterUpdateHook, recoveryCodeAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	recoveryCodeAfterUpdateHooks = []RecoveryCodeHook{}

	AddRecoveryCodeHook(boil.BeforeDeleteHook, recoveryCodeBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	recoveryCodeBeforeDeleteHooks = []RecoveryCodeHook{}

	AddRecoveryCodeHook(boil.AfterDeleteHook, recoveryCodeAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	recoveryCodeAfterDeleteHooks = []RecoveryCodeHook{}

	AddRecoveryCodeHook(boil.BeforeUpsertHook, recoveryCodeBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	recoveryCodeBeforeUpsertHooks = []RecoveryCodeHook{}

	AddRecoveryCodeHook(boil.AfterUpsertHook, recoveryCodeAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	recoveryCodeAfterUpsertHooks = []RecoveryCodeHook{}
}

func testRecoveryCodesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RecoveryCode{}
	if err = randomize.Struct(seed, o, recoveryCodeDBTypes, true, recoveryCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecoveryCode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RecoveryCodes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRecoveryCodesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RecoveryCode{}
	if err = randomize.Struct(seed, o, recoveryCodeDBTypes, true); err != nil {
		t.Errorf("Unable to randomize RecoveryCode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(recoveryCodeColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := RecoveryCodes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRecoveryCodeToOneUserUsingIDUserUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local RecoveryCode
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, recoveryCodeDBTypes, false, recoveryCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecoveryCode struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.IDUser = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.IDUserUser().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddUserHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *User) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := RecoveryCodeSlice{&local}
	if err = local.L.LoadIDUserUser(ctx, tx, false, (*[]*RecoveryCode)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.IDUserUser == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.IDUserUser = nil
	if err = local.L.LoadIDUserUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.IDUserUser == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testRecoveryCodeToOneSetOpUserUsingIDUserUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a RecoveryCode
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, recoveryCodeDBTypes, false, strmangle.SetComplement(recoveryCodePrimaryKeyColumns, recoveryCodeColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetIDUserUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.IDUserUser != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.IDUserRecoveryCodes[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.IDUser != x.ID {
			t.Error("foreign key was wrong value", a.IDUser)
		}

		zero := reflect.Zero(reflect.TypeOf(a.IDUser))
		reflect.Indirect(reflect.ValueOf(&a.IDUser)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.IDUser != x.ID {
			t.Error("foreign key was wrong value", a.IDUser, x.ID)
		}
	}
}

func testRecoveryCodesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RecoveryCode{}
	if err = randomize.Struct(seed, o, recoveryCodeDBTypes, true, recoveryCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecoveryCode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testRecoveryCodesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RecoveryCode{}
	if err = randomize.Struct(seed, o, recoveryCodeDBTypes, true, recoveryCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecoveryCode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RecoveryCodeSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testRecoveryCodesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RecoveryCode{}
	if err = randomize.Struct(seed, o, recoveryCodeDBTypes, true, recoveryCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecoveryCode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := RecoveryCodes().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	recoveryCodeDBTypes = map[string]string{`ID`: `int8`, `Code`: `string`, `IDUser`: `int8`, `IsActive`: `bool`, `ExpiresAt`: `timestamp`, `CreatedAt`: `timestamp`}
	_                   = bytes.MinRead
)

func testRecoveryCodesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(recoveryCodePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(recoveryCodeAllColumns) == len(recoveryCodePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &RecoveryCode{}
	if err = randomize.Struct(seed, o, recoveryCodeDBTypes, true, recoveryCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecoveryCode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RecoveryCodes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, recoveryCodeDBTypes, true, recoveryCodePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize RecoveryCode struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testRecoveryCodesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(recoveryCodeAllColumns) == len(recoveryCodePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &RecoveryCode{}
	if err = randomize.Struct(seed, o, recoveryCodeDBTypes, true, recoveryCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecoveryCode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RecoveryCodes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, recoveryCodeDBTypes, true, recoveryCodePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize RecoveryCode struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(recoveryCodeAllColumns, recoveryCodePrimaryKeyColumns) {
		fields = recoveryCodeAllColumns
	} else {
		fields = strmangle.SetComplement(
			recoveryCodeAllColumns,
			recoveryCodePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := RecoveryCodeSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}
